#!/usr/bin/env node
// Build the zk artifacts.
//
//   node zk/scripts/build.mjs             compile the circuit to its witness generator (about 1 s)
//   node zk/scripts/build.mjs --ceremony  also run a fresh dev Groth16 setup and regenerate
//                                         zk/artifacts/*, the Solidity verifier and the test fixture
//
// The committed zkey comes from a single-contributor dev ceremony run by this
// script. It is fine for tests and a local Anvil; anyone deploying for real
// runs their own ceremony and deploys the verifier it generates.
import { spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ZK = dirname(dirname(fileURLToPath(import.meta.url)));
const ROOT = dirname(ZK);
const BUILD = join(ZK, "build");
const ART = join(ZK, "artifacts");
const CONTRACTS = join(ZK, "contracts");
const CIRCUIT = join(ZK, "circuits", "cap_policy.circom");
const POT_POWER = 12;
const ceremony = process.argv.includes("--ceremony");

const bin = (name) => join(ROOT, "node_modules", ".bin", name);
const circomlibDir = join(ROOT, "node_modules", "circomlib", "circuits");
for (const [what, path] of [["circom2", bin("circom2")], ["snarkjs", bin("snarkjs")], ["circomlib", circomlibDir]]) {
  if (!existsSync(path)) {
    console.error(`${what} not found at ${path}; run npm install first`);
    process.exit(2);
  }
}

function run(cmd, args, label) {
  const r = spawnSync(cmd, args, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
  if (r.status !== 0) {
    process.stderr.write(r.stdout + r.stderr);
    throw new Error(`${label} failed (exit ${r.status})`);
  }
  return r.stdout;
}
const snark = (...a) => run(bin("snarkjs"), a, `snarkjs ${a.slice(0, 2).join(" ")}`);
const rel = (p) => relative(ROOT, p);
const kb = (p) => `${Math.round(statSync(p).size / 1024)} KB`;

mkdirSync(BUILD, { recursive: true });
mkdirSync(ART, { recursive: true });

// 1. Compile: r1cs (constraints), wasm (witness generator), sym (signal names).
const out = run(bin("circom2"), [CIRCUIT, "--r1cs", "--wasm", "--sym", "-o", BUILD, "-l", circomlibDir], "circom2");
const constraints = Number(/non-linear constraints: (\d+)/.exec(out)?.[1] ?? NaN);
console.log(`compiled ${rel(CIRCUIT)} -> ${rel(BUILD)} (${constraints} non-linear constraints)`);

const zkey = join(ART, "cap_policy.zkey");
const vkey = join(ART, "verification_key.json");
const info = join(ART, "build-info.json");
const verifier = join(CONTRACTS, "src", "CapPolicyVerifier.sol");
const fixture = join(CONTRACTS, "test", "fixtures", "cap-fixture.json");

if (!ceremony && existsSync(zkey)) {
  const prior = existsSync(info) ? JSON.parse(readFileSync(info, "utf8")) : null;
  if (prior && prior.constraints !== constraints) {
    console.warn(
      `warning: the circuit now has ${constraints} constraints, the committed zkey was made for ${prior.constraints}; run: npm run zk:ceremony`,
    );
  }
  console.log(`witness generator ready: ${rel(join(BUILD, "cap_policy_js", "cap_policy.wasm"))}`);
  process.exit(0);
}

// 2. Dev ceremony: powers of tau, then the circuit-specific Groth16 setup.
const entropy = () => randomBytes(32).toString("hex");
const pot0 = join(BUILD, `pot${POT_POWER}_0000.ptau`);
const pot1 = join(BUILD, `pot${POT_POWER}_0001.ptau`);
const potFinal = join(BUILD, `pot${POT_POWER}_final.ptau`);
const zkey0 = join(BUILD, "cap_policy_0000.zkey");
console.log(`dev ceremony: powers of tau 2^${POT_POWER} (about 20 s) ...`);
snark("powersoftau", "new", "bn128", String(POT_POWER), pot0);
snark("powersoftau", "contribute", pot0, pot1, "--name=pi-crypto-gate dev", `-e=${entropy()}`);
snark("powersoftau", "prepare", "phase2", pot1, potFinal);
snark("groth16", "setup", join(BUILD, "cap_policy.r1cs"), potFinal, zkey0);
snark("zkey", "contribute", zkey0, zkey, "--name=pi-crypto-gate dev", `-e=${entropy()}`);
snark("zkey", "export", "verificationkey", zkey, vkey);
snark("zkey", "export", "solidityverifier", zkey, verifier);
const generated = readFileSync(verifier, "utf8").replace(
  /^(\/\/ SPDX-License-Identifier: GPL-3\.0\n)/,
  "$1// Generated by snarkjs from zk/circuits/cap_policy.circom (Groth16, dev ceremony).\n" +
    "// Regenerate together with zk/artifacts/* and the test fixture: npm run zk:ceremony\n",
);
writeFileSync(verifier, generated);
console.log(`proving key ${rel(zkey)} (${kb(zkey)}), verification key ${rel(vkey)}, verifier ${rel(verifier)}`);

// 3. Fixture: one real proof for the Foundry tests, pinned to a test account
//    and chain id. The tests deploy the account at exactly that address.
const { paramsCommit, toBytes32 } = await import("../src/commit.js");
const { proveCapPolicy, verifyCapPolicy } = await import("../src/prove.js");
const { buildEnvelope } = await import("../src/envelope.js");
const { terminate } = await import("../src/deps.js");
const F = {
  version: 1,
  account: "0x000000000000000000000000000000000000ca9e",
  chainId: 31337,
  to: "0x3333333333333333333333333333333333333333",
  cap: 250000000n, // 250 USDC
  salt: 1234567890123456789012345678901234567890n,
  value: 150000000n, // 150 USDC
  nonce: "0x0000000000000000000000000000000000000000000000000000000000000001",
};
const commit = await paramsCommit({ version: F.version, cap: F.cap, salt: F.salt });
const paths = { wasm: join(BUILD, "cap_policy_js", "cap_policy.wasm"), zkey };
const proved = await proveCapPolicy({ ...F, paramsCommit: commit }, paths);
if (!(await verifyCapPolicy({ vkey, publicSignals: proved.publicSignals, proof: proved.proof }))) {
  throw new Error("fixture proof does not verify");
}
const envelope = buildEnvelope({ ...proved, to: F.to, value: F.value, validAfter: 0, validBefore: (1n << 256n) - 1n, nonce: F.nonce });
writeFileSync(
  fixture,
  JSON.stringify(
    {
      note: "one real Groth16 proof from the dev ceremony; regenerate with npm run zk:ceremony",
      version: F.version,
      account: F.account,
      chainId: F.chainId,
      to: F.to,
      value: Number(F.value),
      cap: Number(F.cap),
      salt: F.salt.toString(),
      paramsCommit: commit.toString(),
      paramsCommitHex: toBytes32(commit),
      nonce: F.nonce,
      a: proved.a,
      b: proved.b,
      c: proved.c,
      publicSignals: proved.publicSignals,
      envelope: envelope.envelope,
    },
    null,
    2,
  ) + "\n",
);
writeFileSync(
  info,
  JSON.stringify({ builtAt: new Date().toISOString(), circuit: rel(CIRCUIT), constraints, potPower: POT_POWER, ceremony: "dev, single contributor" }, null, 2) + "\n",
);
console.log(`fixture ${rel(fixture)} written; ${rel(info)} records ${constraints} constraints`);
await terminate();
process.exit(0);
